using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using NSharpLang.Compiler.Ast;

namespace NSharpLang.Compiler;

public static class CompilationStubEmitter
{
    public static string Generate(ProjectConfig config, IEnumerable<string> sourceFiles)
    {
        ArgumentNullException.ThrowIfNull(config);
        ArgumentNullException.ThrowIfNull(sourceFiles);

        var compilationUnits = new List<CompilationUnit>();
        foreach (var sourceFile in sourceFiles
                     .Where(path => !string.IsNullOrWhiteSpace(path) && File.Exists(path))
                     .Distinct(StringComparer.OrdinalIgnoreCase))
        {
            var source = File.ReadAllText(sourceFile);
            var lexer = new Lexer(source, sourceFile);
            var parser = new Parser(lexer.Tokenize(), sourceFile, source);
            var parseResult = parser.ParseCompilationUnit();
            if (parseResult.Success && parseResult.CompilationUnit != null)
            {
                compilationUnits.Add(parseResult.CompilationUnit);
            }
        }

        return new Writer(config, compilationUnits).Write();
    }

    private sealed class Writer(ProjectConfig config, IReadOnlyList<CompilationUnit> compilationUnits)
    {
        private readonly ProjectConfig _config = config;
        private readonly IReadOnlyList<CompilationUnit> _compilationUnits = compilationUnits;
        private readonly StringBuilder _output = new();
        private int _indentLevel;

        public string Write()
        {
            _output.AppendLine("// <auto-generated />");
            _output.AppendLine("#nullable enable");
            _output.AppendLine();

            EmitFileImports();

            var topLevelFunctions = _compilationUnits
                .SelectMany(unit => unit.Declarations.OfType<FunctionDeclaration>()
                    .Select(function => new TopLevelFunctionStub(GetNamespaceName(unit), function)))
                .ToList();
            var hasDeclaredEntryPoint = HasDeclaredEntryPoint();
            var emittedMain = EmitProgramStub(topLevelFunctions);

            var namespaceGroups = _compilationUnits
                .GroupBy(GetNamespaceName, StringComparer.Ordinal)
                .OrderBy(group => string.IsNullOrEmpty(group.Key) ? 0 : 1)
                .ThenBy(group => group.Key, StringComparer.Ordinal);

            var wroteNamespaceContent = false;
            foreach (var group in namespaceGroups)
            {
                var declarations = group
                    .SelectMany(unit => unit.Declarations)
                    .Where(declaration => declaration is not FunctionDeclaration and not TestDeclaration and not SetupDeclaration and not TeardownDeclaration and not PreprocessorDeclaration)
                    .ToList();

                if (declarations.Count == 0)
                {
                    continue;
                }

                if (wroteNamespaceContent || topLevelFunctions.Count > 0)
                {
                    _output.AppendLine();
                }

                if (!string.IsNullOrEmpty(group.Key))
                {
                    WriteLine($"namespace {group.Key}");
                    WriteLine("{");
                    _indentLevel++;
                }

                EmitNamespaceMembers(declarations);

                if (!string.IsNullOrEmpty(group.Key))
                {
                    _indentLevel--;
                    WriteLine("}");
                }

                wroteNamespaceContent = true;
            }

            if (!emittedMain
                && !hasDeclaredEntryPoint
                && string.Equals(_config.OutputType, "exe", StringComparison.OrdinalIgnoreCase))
            {
                if (topLevelFunctions.Count > 0 || wroteNamespaceContent)
                {
                    _output.AppendLine();
                }

                WriteLine("internal static class __NSharpIlStub");
                WriteLine("{");
                _indentLevel++;
                WriteLine("public static void Main(string[] args)");
                WriteLine("{");
                WriteLine("}");
                _indentLevel--;
                WriteLine("}");
            }

            return _output.ToString();
        }

        private void EmitFileImports()
        {
            var usingDirectives = new SortedSet<string>(StringComparer.Ordinal)
            {
                "using System;"
            };

            foreach (var unit in _compilationUnits)
            {
                foreach (var import in unit.Imports)
                {
                    if (string.IsNullOrWhiteSpace(import.Namespace))
                    {
                        continue;
                    }

                    usingDirectives.Add(import.Alias == null
                        ? $"using {import.Namespace};"
                        : $"using {import.Alias} = {import.Namespace};");
                }
            }

            foreach (var namespaceName in _compilationUnits
                         .Select(GetNamespaceName)
                         .Where(namespaceName => !string.IsNullOrWhiteSpace(namespaceName))
                         .Distinct(StringComparer.Ordinal)
                         .OrderBy(namespaceName => namespaceName, StringComparer.Ordinal))
            {
                usingDirectives.Add($"using {namespaceName};");
            }

            if (usingDirectives.Count == 0)
            {
                return;
            }

            foreach (var usingDirective in usingDirectives)
            {
                _output.AppendLine(usingDirective);
            }

            _output.AppendLine();
        }

        private void EmitNamespaceMembers(IReadOnlyList<Declaration> declarations)
        {
            var typeAliases = declarations.OfType<TypeAliasDeclaration>().ToList();
            foreach (var alias in typeAliases)
            {
                WriteLine($"using {alias.Name} = {TranspileTypeReference(alias.Type)};");
            }

            if (typeAliases.Count > 0 && declarations.Any(declaration => declaration is not TypeAliasDeclaration))
            {
                _output.AppendLine();
            }

            var firstType = true;
            foreach (var declaration in declarations)
            {
                if (declaration is TypeAliasDeclaration)
                {
                    continue;
                }

                if (!firstType)
                {
                    _output.AppendLine();
                }

                EmitDeclaration(declaration, isInterfaceMember: false, isNestedType: false, containingTypeName: null);
                firstType = false;
            }
        }

        private bool EmitProgramStub(IReadOnlyList<TopLevelFunctionStub> functions)
        {
            if (functions.Count == 0)
            {
                return false;
            }

            var emittedMain = false;
            var groupedFunctions = functions
                .GroupBy(function => function.Namespace, StringComparer.Ordinal)
                .OrderBy(group => string.IsNullOrEmpty(group.Key) ? 0 : 1)
                .ThenBy(group => group.Key, StringComparer.Ordinal)
                .ToList();

            for (int groupIndex = 0; groupIndex < groupedFunctions.Count; groupIndex++)
            {
                var group = groupedFunctions[groupIndex];
                if (groupIndex > 0)
                {
                    _output.AppendLine();
                }

                if (!string.IsNullOrEmpty(group.Key))
                {
                    WriteLine($"namespace {group.Key}");
                    WriteLine("{");
                    _indentLevel++;
                }

                WriteLine("internal static partial class __NSharpTopLevelFunctions");
                WriteLine("{");
                _indentLevel++;

                var groupedFunctionList = group.ToList();
                for (int i = 0; i < groupedFunctionList.Count; i++)
                {
                    var function = groupedFunctionList[i].Function;
                    emittedMain |= string.Equals(function.Name, "main", StringComparison.OrdinalIgnoreCase);
                    EmitFunction(function, isInterfaceMember: false, isTopLevelFunction: true, containingTypeName: "__NSharpTopLevelFunctions");
                    if (i < groupedFunctionList.Count - 1)
                    {
                        _output.AppendLine();
                    }
                }

                _indentLevel--;
                WriteLine("}");

                if (!string.IsNullOrEmpty(group.Key))
                {
                    _indentLevel--;
                    WriteLine("}");
                }
            }

            return emittedMain;
        }

        private bool HasDeclaredEntryPoint()
        {
            return _compilationUnits.Any(unit => ContainsDeclaredEntryPoint(unit.Declarations));
        }

        private static bool ContainsDeclaredEntryPoint(IEnumerable<Declaration> declarations)
        {
            foreach (var declaration in declarations)
            {
                switch (declaration)
                {
                    case FunctionDeclaration functionDeclaration when IsDeclaredEntryPoint(functionDeclaration):
                        return true;
                    case ClassDeclaration classDeclaration when ContainsDeclaredEntryPoint(classDeclaration.Members):
                        return true;
                    case StructDeclaration structDeclaration when ContainsDeclaredEntryPoint(structDeclaration.Members):
                        return true;
                    case RecordDeclaration recordDeclaration when ContainsDeclaredEntryPoint(recordDeclaration.Members):
                        return true;
                    case InterfaceDeclaration interfaceDeclaration when ContainsDeclaredEntryPoint(interfaceDeclaration.Members):
                        return true;
                }
            }

            return false;
        }

        private static bool IsDeclaredEntryPoint(FunctionDeclaration functionDeclaration)
        {
            return functionDeclaration.Modifiers.HasFlag(Modifiers.Static)
                && string.Equals(functionDeclaration.Name, "main", StringComparison.OrdinalIgnoreCase);
        }

        private void EmitDeclaration(Declaration declaration, bool isInterfaceMember, bool isNestedType, string? containingTypeName)
        {
            switch (declaration)
            {
                case ClassDeclaration classDeclaration:
                    EmitClass(classDeclaration, isNestedType);
                    break;
                case StructDeclaration structDeclaration:
                    EmitStruct(structDeclaration, isNestedType);
                    break;
                case RecordDeclaration recordDeclaration:
                    EmitRecord(recordDeclaration, isNestedType);
                    break;
                case InterfaceDeclaration interfaceDeclaration:
                    EmitInterface(interfaceDeclaration, isNestedType);
                    break;
                case EnumDeclaration enumDeclaration:
                    EmitEnum(enumDeclaration, isNestedType);
                    break;
                case UnionDeclaration unionDeclaration:
                    EmitUnion(unionDeclaration, isNestedType);
                    break;
                case NewtypeDeclaration newtypeDeclaration:
                    EmitNewtype(newtypeDeclaration, isNestedType);
                    break;
                case FieldDeclaration fieldDeclaration:
                    EmitField(fieldDeclaration, isInterfaceMember);
                    break;
                case PropertyDeclaration propertyDeclaration:
                    EmitProperty(propertyDeclaration, isInterfaceMember);
                    break;
                case ConstructorDeclaration constructorDeclaration:
                    EmitConstructor(constructorDeclaration, isInterfaceMember, containingTypeName);
                    break;
                case IndexerDeclaration indexerDeclaration:
                    EmitIndexer(indexerDeclaration, isInterfaceMember);
                    break;
                case FunctionDeclaration functionDeclaration:
                    EmitFunction(functionDeclaration, isInterfaceMember, isTopLevelFunction: false, containingTypeName: containingTypeName);
                    break;
            }
        }

        private void EmitClass(ClassDeclaration declaration, bool isNestedType)
        {
            var modifiers = GetTypeModifierString(declaration.Modifiers, isNestedType, declaration.Name);
            var typeParameters = FormatTypeParameters(declaration.TypeParameters);
            var bases = new List<string>();
            if (declaration.BaseClass != null)
            {
                bases.Add(TranspileTypeReference(declaration.BaseClass));
            }

            bases.AddRange(declaration.Interfaces.Select(TranspileTypeReference));

            Write($"{modifiers}class {declaration.Name}{typeParameters}");
            if (declaration.PrimaryConstructorParameters != null && declaration.PrimaryConstructorParameters.Count > 0)
            {
                _output.Append($"({string.Join(", ", declaration.PrimaryConstructorParameters.Select(FormatParameter))})");
            }

            if (bases.Count > 0)
            {
                _output.Append($" : {string.Join(", ", bases)}");
            }

            WriteLine();
            WriteLine("{");
            _indentLevel++;
            EmitTypeMembers(declaration.Members, isInterface: false, declaration.Name);
            _indentLevel--;
            WriteLine("}");
        }

        private void EmitStruct(StructDeclaration declaration, bool isNestedType)
        {
            var modifiers = GetTypeModifierString(declaration.Modifiers, isNestedType, declaration.Name);
            var typeParameters = FormatTypeParameters(declaration.TypeParameters);
            var bases = declaration.Interfaces.Select(TranspileTypeReference).ToList();

            Write($"{modifiers}struct {declaration.Name}{typeParameters}");
            if (declaration.PrimaryConstructorParameters != null && declaration.PrimaryConstructorParameters.Count > 0)
            {
                _output.Append($"({string.Join(", ", declaration.PrimaryConstructorParameters.Select(FormatParameter))})");
            }

            if (bases.Count > 0)
            {
                _output.Append($" : {string.Join(", ", bases)}");
            }

            WriteLine();
            WriteLine("{");
            _indentLevel++;
            EmitTypeMembers(declaration.Members, isInterface: false, declaration.Name);
            _indentLevel--;
            WriteLine("}");
        }

        private void EmitRecord(RecordDeclaration declaration, bool isNestedType)
        {
            var modifiers = GetTypeModifierString(declaration.Modifiers, isNestedType, declaration.Name, forceSealed: true);
            var typeParameters = FormatTypeParameters(declaration.TypeParameters);
            var bases = declaration.Interfaces.Select(TranspileTypeReference).ToList();
            var keyword = declaration.IsStruct ? "record struct" : "record";

            Write($"{modifiers}{keyword} {declaration.Name}{typeParameters}");
            if (declaration.PrimaryConstructorParameters != null && declaration.PrimaryConstructorParameters.Count > 0)
            {
                _output.Append($"({string.Join(", ", declaration.PrimaryConstructorParameters.Select(FormatParameter))})");
            }

            if (bases.Count > 0)
            {
                _output.Append($" : {string.Join(", ", bases)}");
            }

            WriteLine();
            WriteLine("{");
            _indentLevel++;

            if (declaration.PrimaryConstructorParameters != null && declaration.PrimaryConstructorParameters.Count > 0)
            {
                foreach (var parameter in declaration.PrimaryConstructorParameters)
                {
                    WriteLine($"public {TranspileTypeReference(parameter.Type)} {parameter.Name} {{ get; }}");
                }

                if (declaration.Members.Count > 0)
                {
                    _output.AppendLine();
                }
            }

            EmitTypeMembers(declaration.Members, isInterface: false, declaration.Name);
            _indentLevel--;
            WriteLine("}");
        }

        private void EmitInterface(InterfaceDeclaration declaration, bool isNestedType)
        {
            var modifiers = GetTypeModifierString(declaration.Modifiers, isNestedType, declaration.Name);
            var typeParameters = FormatTypeParameters(declaration.TypeParameters);

            Write($"{modifiers}interface {declaration.Name}{typeParameters}");
            if (declaration.BaseInterfaces.Count > 0)
            {
                _output.Append($" : {string.Join(", ", declaration.BaseInterfaces.Select(TranspileTypeReference))}");
            }

            WriteLine();
            WriteLine("{");
            _indentLevel++;
            EmitTypeMembers(declaration.Members, isInterface: true, declaration.Name);
            _indentLevel--;
            WriteLine("}");
        }

        private void EmitEnum(EnumDeclaration declaration, bool isNestedType)
        {
            var modifiers = GetTypeModifierString(declaration.Modifiers, isNestedType, declaration.Name);
            if (declaration.Type == EnumType.String)
            {
                WriteLine($"{modifiers}static class {declaration.Name}");
                WriteLine("{");
                _indentLevel++;
                foreach (var member in declaration.Members)
                {
                    var value = TryFormatConstantExpression(member.Value) ?? $"\"{EscapeString(member.Name)}\"";
                    WriteLine($"{VisibilityConventions.GetMemberVisibilityKeyword(member.Name, Modifiers.None)} const string {member.Name} = {value};");
                }
                _indentLevel--;
                WriteLine("}");
                return;
            }

            WriteLine($"{modifiers}enum {declaration.Name}");
            WriteLine("{");
            _indentLevel++;
            for (int i = 0; i < declaration.Members.Count; i++)
            {
                var member = declaration.Members[i];
                var value = TryFormatConstantExpression(member.Value);
                WriteLine(value == null ? $"{member.Name}," : $"{member.Name} = {value},");
            }
            _indentLevel--;
            WriteLine("}");
        }

        private void EmitUnion(UnionDeclaration declaration, bool isNestedType)
        {
            var modifiers = GetTypeModifierString(declaration.Modifiers, isNestedType, declaration.Name, forceAbstract: true);
            WriteLine($"{modifiers}class {declaration.Name}");
            WriteLine("{");
            _indentLevel++;
            WriteLine($"protected {declaration.Name}()");
            WriteLine("{");
            WriteLine("}");

            foreach (var unionCase in declaration.Cases)
            {
                _output.AppendLine();
                WriteLine($"{VisibilityConventions.GetNestedTypeVisibilityKeyword(unionCase.Name, Modifiers.None)} sealed class {unionCase.Name} : {declaration.Name}");
                WriteLine("{");
                _indentLevel++;
                if (unionCase.Properties != null)
                {
                    foreach (var property in unionCase.Properties)
                    {
                        WriteLine($"{VisibilityConventions.GetMemberVisibilityKeyword(property.Name, Modifiers.None)} {TranspileTypeReference(property.Type)} {property.Name};");
                    }
                }
                WriteLine($"public {unionCase.Name}()");
                WriteLine("{");
                WriteLine("}");
                _indentLevel--;
                WriteLine("}");
            }

            _indentLevel--;
            WriteLine("}");
        }

        private void EmitNewtype(NewtypeDeclaration declaration, bool isNestedType)
        {
            var modifiers = GetTypeModifierString(Modifiers.None, isNestedType, declaration.Name, forceReadonly: true);
            WriteLine($"{modifiers}record struct {declaration.Name}({TranspileTypeReference(declaration.UnderlyingType)} Value);");
        }

        private void EmitTypeMembers(IReadOnlyList<Declaration> members, bool isInterface, string containingTypeName)
        {
            for (int i = 0; i < members.Count; i++)
            {
                EmitDeclaration(members[i], isInterface, isNestedType: true, containingTypeName);
                if (i < members.Count - 1)
                {
                    _output.AppendLine();
                }
            }
        }

        private void EmitField(FieldDeclaration declaration, bool isInterfaceMember)
        {
            if (isInterfaceMember)
            {
                return;
            }

            if (declaration.PropertyModifier.HasFlag(PropertyModifier.Required) || declaration.PropertyModifier.HasFlag(PropertyModifier.Init))
            {
                var modifiers = GetMemberModifierString(declaration.Modifiers, declaration.Name);
                if (declaration.PropertyModifier.HasFlag(PropertyModifier.Required))
                {
                    modifiers += "required ";
                }

                var accessors = declaration.PropertyModifier.HasFlag(PropertyModifier.Init)
                    ? "{ get; init; }"
                    : "{ get; set; }";
                WriteLine($"{modifiers}{ResolveFieldType(declaration)} {declaration.Name} {accessors}");
                return;
            }

            var fieldModifiers = GetMemberModifierString(declaration.Modifiers, declaration.Name);
            if (declaration.Modifiers.HasFlag(Modifiers.Readonly) || declaration.PropertyModifier.HasFlag(PropertyModifier.Readonly))
            {
                fieldModifiers += "readonly ";
            }

            WriteLine($"{fieldModifiers}{ResolveFieldType(declaration)} {declaration.Name};");
        }

        private void EmitProperty(PropertyDeclaration declaration, bool isInterfaceMember)
        {
            var modifiers = isInterfaceMember ? string.Empty : GetMemberModifierString(declaration.Modifiers, declaration.Name);
            if (declaration.PropertyModifier.HasFlag(PropertyModifier.Required) && !isInterfaceMember)
            {
                modifiers += "required ";
            }

            var typeName = TranspileTypeReference(declaration.Type);

            if (isInterfaceMember)
            {
                var accessors = GetPropertyAccessorList(declaration);
                WriteLine($"{typeName} {declaration.Name} {accessors}");
                return;
            }

            if (declaration.ExpressionBody != null)
            {
                WriteLine($"{modifiers}{typeName} {declaration.Name} => throw new global::System.NotSupportedException();");
                return;
            }

            if (declaration.GetBody == null && declaration.SetBody == null)
            {
                var accessors = declaration.PropertyModifier.HasFlag(PropertyModifier.Init)
                    ? "{ get; init; }"
                    : "{ get; set; }";
                WriteLine($"{modifiers}{typeName} {declaration.Name} {accessors}");
                return;
            }

            WriteLine($"{modifiers}{typeName} {declaration.Name}");
            WriteLine("{");
            _indentLevel++;
            if (declaration.GetBody != null)
            {
                WriteLine("get => throw new global::System.NotSupportedException();");
            }

            if (declaration.SetBody != null && !declaration.PropertyModifier.HasFlag(PropertyModifier.Readonly))
            {
                WriteLine(declaration.PropertyModifier.HasFlag(PropertyModifier.Init)
                    ? "init => throw new global::System.NotSupportedException();"
                    : "set => throw new global::System.NotSupportedException();");
            }
            _indentLevel--;
            WriteLine("}");
        }

        private void EmitConstructor(ConstructorDeclaration declaration, bool isInterfaceMember, string? containingTypeName)
        {
            if (isInterfaceMember)
            {
                return;
            }

            var modifiers = GetConstructorModifierString(declaration.Modifiers);
            var parameters = string.Join(", ", declaration.Parameters.Select(FormatParameter));
            WriteLine($"{modifiers}{containingTypeName ?? "__NSharpStub"}({parameters})");
            WriteLine("{");
            WriteLine("}");
        }

        private void EmitIndexer(IndexerDeclaration declaration, bool isInterfaceMember)
        {
            var modifiers = isInterfaceMember ? string.Empty : GetIndexerModifierString(declaration.Modifiers);
            var parameters = string.Join(", ", declaration.Parameters.Select(FormatParameter));
            var typeName = TranspileTypeReference(declaration.Type);

            if (isInterfaceMember)
            {
                WriteLine($"{typeName} this[{parameters}] {{ {GetIndexerAccessorList(declaration)} }}");
                return;
            }

            WriteLine($"{modifiers}{typeName} this[{parameters}]");
            WriteLine("{");
            _indentLevel++;
            if (declaration.GetBody != null)
            {
                WriteLine("get => throw new global::System.NotSupportedException();");
            }

            if (declaration.SetBody != null)
            {
                WriteLine("set => throw new global::System.NotSupportedException();");
            }
            _indentLevel--;
            WriteLine("}");
        }

        private void EmitFunction(FunctionDeclaration declaration, bool isInterfaceMember, bool isTopLevelFunction, string? containingTypeName)
        {
            var signature = FormatFunctionSignature(declaration, isInterfaceMember, isTopLevelFunction, containingTypeName);
            var constraints = FormatGenericConstraints(declaration.Constraints);

            if (isInterfaceMember || declaration.Modifiers.HasFlag(Modifiers.Abstract))
            {
                WriteLine($"{signature}{constraints};");
                return;
            }

            WriteLine($"{signature}{constraints} => throw new global::System.NotSupportedException();");
        }

        private string FormatFunctionSignature(FunctionDeclaration declaration, bool isInterfaceMember, bool isTopLevelFunction, string? containingTypeName)
        {
            if (declaration.IsConversionOperator)
            {
                var operatorModifiers = isInterfaceMember ? string.Empty : "public static ";
                var conversionKeyword = declaration.IsImplicitConversion ? "implicit" : "explicit";
                var parameter = declaration.Parameters.Count > 0
                    ? FormatParameter(declaration.Parameters[0])
                    : $"{containingTypeName ?? "__NSharpStub"} value";
                return $"{operatorModifiers}{conversionKeyword} operator {TranspileTypeReference(declaration.ReturnType ?? new SimpleTypeReference("object"))}({parameter})";
            }

            if (declaration.IsOperatorOverload)
            {
                var operatorModifiers = isInterfaceMember ? string.Empty : "public static ";
                var returnType = TranspileTypeReference(declaration.ReturnType ?? new SimpleTypeReference("void"));
                var parameters = string.Join(", ", declaration.Parameters.Select(FormatParameter));
                return $"{operatorModifiers}{returnType} operator {declaration.OperatorSymbol}({parameters})";
            }

            var methodName = isTopLevelFunction && string.Equals(declaration.Name, "main", StringComparison.OrdinalIgnoreCase)
                ? "Main"
                : declaration.Name;
            var returnTypeName = TranspileTypeReference(declaration.ReturnType ?? new SimpleTypeReference("void"));
            var typeParameters = FormatTypeParameters(declaration.TypeParameters);
            var parametersList = string.Join(", ", declaration.Parameters.Select(FormatParameter));

            if (isInterfaceMember)
            {
                return $"{returnTypeName} {methodName}{typeParameters}({parametersList})";
            }

            var modifiers = isTopLevelFunction
                ? $"{VisibilityConventions.GetMemberVisibilityKeyword(declaration.Name, declaration.Modifiers)} static "
                : GetMethodModifierString(declaration.Modifiers, declaration.Name);
            return $"{modifiers}{returnTypeName} {methodName}{typeParameters}({parametersList})";
        }

        private string GetTypeModifierString(Modifiers modifiers, bool isNestedType, string name, bool forceAbstract = false, bool forceSealed = false, bool forceReadonly = false)
        {
            var parts = new List<string>();
            parts.Add(GetTypeVisibilityKeyword(modifiers, isNestedType, name));

            if (modifiers.HasFlag(Modifiers.Static))
            {
                parts.Add("static");
            }
            else
            {
                if (modifiers.HasFlag(Modifiers.Abstract) || forceAbstract)
                {
                    parts.Add("abstract");
                }

                if (modifiers.HasFlag(Modifiers.Sealed) || forceSealed)
                {
                    parts.Add("sealed");
                }
            }

            if (modifiers.HasFlag(Modifiers.Partial))
            {
                parts.Add("partial");
            }

            if (modifiers.HasFlag(Modifiers.Readonly) || forceReadonly)
            {
                parts.Add("readonly");
            }

            return string.Join(" ", parts.Where(part => !string.IsNullOrWhiteSpace(part))) + " ";
        }

        private static string GetTypeVisibilityKeyword(Modifiers modifiers, bool isNestedType, string name)
        {
            return isNestedType
                ? VisibilityConventions.GetNestedTypeVisibilityKeyword(name, modifiers)
                : VisibilityConventions.GetTopLevelTypeVisibilityKeyword(name, modifiers);
        }

        private static string GetMethodModifierString(Modifiers modifiers, string name)
        {
            var parts = new List<string> { GetMemberVisibilityKeyword(modifiers, name, defaultToPublic: false) };

            if (modifiers.HasFlag(Modifiers.Static))
            {
                parts.Add("static");
            }

            if (modifiers.HasFlag(Modifiers.Virtual))
            {
                parts.Add("virtual");
            }

            if (modifiers.HasFlag(Modifiers.Override))
            {
                parts.Add("override");
            }

            if (modifiers.HasFlag(Modifiers.Abstract))
            {
                parts.Add("abstract");
            }

            return string.Join(" ", parts.Where(part => !string.IsNullOrWhiteSpace(part))) + " ";
        }

        private static string GetMemberModifierString(Modifiers modifiers, string name)
        {
            var parts = new List<string> { GetMemberVisibilityKeyword(modifiers, name, defaultToPublic: false) };

            if (modifiers.HasFlag(Modifiers.Static))
            {
                parts.Add("static");
            }

            return string.Join(" ", parts.Where(part => !string.IsNullOrWhiteSpace(part))) + " ";
        }

        private static string GetConstructorModifierString(Modifiers modifiers)
        {
            if (modifiers.HasFlag(Modifiers.Private))
            {
                return "private ";
            }

            if (modifiers.HasFlag(Modifiers.Protected) && modifiers.HasFlag(Modifiers.Internal))
            {
                return "protected internal ";
            }

            if (modifiers.HasFlag(Modifiers.Protected))
            {
                return "protected ";
            }

            if (modifiers.HasFlag(Modifiers.Internal))
            {
                return "internal ";
            }

            return "public ";
        }

        private static string GetIndexerModifierString(Modifiers modifiers)
        {
            if (modifiers.HasFlag(Modifiers.Private))
            {
                return "private ";
            }

            if (modifiers.HasFlag(Modifiers.Protected) && modifiers.HasFlag(Modifiers.Internal))
            {
                return "protected internal ";
            }

            if (modifiers.HasFlag(Modifiers.Protected))
            {
                return "protected ";
            }

            if (modifiers.HasFlag(Modifiers.Internal))
            {
                return "internal ";
            }

            return "public ";
        }

        private static string GetMemberVisibilityKeyword(Modifiers modifiers, string name, bool defaultToPublic)
        {
            if (modifiers.HasFlag(Modifiers.Private))
            {
                return "private";
            }

            if (modifiers.HasFlag(Modifiers.Protected) && modifiers.HasFlag(Modifiers.Internal))
            {
                return "protected internal";
            }

            if (modifiers.HasFlag(Modifiers.Protected))
            {
                return "protected";
            }

            if (modifiers.HasFlag(Modifiers.Internal))
            {
                return "internal";
            }

            if (modifiers.HasFlag(Modifiers.Public))
            {
                return "public";
            }

            if (defaultToPublic)
            {
                return "public";
            }

            return VisibilityConventions.GetMemberVisibilityKeyword(name, modifiers);
        }

        private static string GetPropertyAccessorList(PropertyDeclaration declaration)
        {
            var parts = new List<string>();
            if (declaration.GetBody != null || declaration.ExpressionBody != null || declaration.SetBody == null)
            {
                parts.Add("get;");
            }

            if (declaration.SetBody != null && !declaration.PropertyModifier.HasFlag(PropertyModifier.Readonly))
            {
                parts.Add(declaration.PropertyModifier.HasFlag(PropertyModifier.Init) ? "init;" : "set;");
            }

            return "{ " + string.Join(" ", parts) + " }";
        }

        private static string GetIndexerAccessorList(IndexerDeclaration declaration)
        {
            var parts = new List<string>();
            if (declaration.GetBody != null)
            {
                parts.Add("get;");
            }

            if (declaration.SetBody != null)
            {
                parts.Add("set;");
            }

            return string.Join(" ", parts);
        }

        private static string ResolveFieldType(FieldDeclaration declaration)
        {
            if (declaration.Type != null)
            {
                return TranspileTypeReference(declaration.Type);
            }

            return InferExpressionType(declaration.Initializer);
        }

        private static string InferExpressionType(Expression? expression)
        {
            return expression switch
            {
                IntLiteralExpression => "int",
                FloatLiteralExpression => "double",
                StringLiteralExpression => "string",
                BoolLiteralExpression => "bool",
                NullLiteralExpression => "object?",
                _ => "object"
            };
        }

        private static string FormatTypeParameters(IReadOnlyList<TypeParameter>? typeParameters)
        {
            return typeParameters != null && typeParameters.Count > 0
                ? $"<{string.Join(", ", typeParameters.Select(parameter => parameter.Name))}>"
                : string.Empty;
        }

        private static string FormatGenericConstraints(IReadOnlyList<GenericConstraint>? constraints)
        {
            if (constraints == null || constraints.Count == 0)
            {
                return string.Empty;
            }

            var builder = new StringBuilder();
            foreach (var constraint in constraints)
            {
                var parts = constraint.Constraints
                    .Select(TranspileTypeReference)
                    .ToList();

                if (constraint.SpecialConstraints.HasFlag(SpecialConstraintKind.Class))
                {
                    parts.Add("class");
                }

                if (constraint.SpecialConstraints.HasFlag(SpecialConstraintKind.Struct))
                {
                    parts.Add("struct");
                }

                if (constraint.SpecialConstraints.HasFlag(SpecialConstraintKind.New))
                {
                    parts.Add("new()");
                }

                builder.Append($" where {constraint.TypeParameter} : {string.Join(", ", parts)}");
            }

            return builder.ToString();
        }

        private static string FormatParameter(Parameter parameter)
        {
            var modifier = parameter.Modifier switch
            {
                ParameterModifier.Ref => "ref ",
                ParameterModifier.Out => "out ",
                ParameterModifier.Params => "params ",
                _ => parameter.IsThis ? "this " : string.Empty
            };

            var defaultValue = TryFormatConstantExpression(parameter.DefaultValue);
            return defaultValue == null
                ? $"{modifier}{TranspileTypeReference(parameter.Type)} {parameter.Name}"
                : $"{modifier}{TranspileTypeReference(parameter.Type)} {parameter.Name} = {defaultValue}";
        }

        private static string? TryFormatConstantExpression(Expression? expression)
        {
            return expression switch
            {
                null => null,
                IntLiteralExpression literal => literal.Value,
                FloatLiteralExpression literal => literal.Value,
                StringLiteralExpression literal => $"\"{EscapeString(literal.Value)}\"",
                BoolLiteralExpression literal => literal.Value ? "true" : "false",
                NullLiteralExpression => "null",
                UnaryExpression { Operator: UnaryOperator.Negate, Operand: IntLiteralExpression literal } => "-" + literal.Value,
                UnaryExpression { Operator: UnaryOperator.Negate, Operand: FloatLiteralExpression literal } => "-" + literal.Value,
                MemberAccessExpression memberAccess when memberAccess.Object is IdentifierExpression identifier
                    => $"{identifier.Name}.{memberAccess.MemberName}",
                IdentifierExpression identifier => identifier.Name,
                _ => null
            };
        }

        private static string EscapeString(string value)
        {
            return value
                .Replace("\\", "\\\\", StringComparison.Ordinal)
                .Replace("\"", "\\\"", StringComparison.Ordinal)
                .Replace("\r", "\\r", StringComparison.Ordinal)
                .Replace("\n", "\\n", StringComparison.Ordinal)
                .Replace("\t", "\\t", StringComparison.Ordinal);
        }

        private static string TranspileTypeReference(TypeReference typeReference)
        {
            return typeReference switch
            {
                SimpleTypeReference simple => simple.Name,
                GenericTypeReference generic => $"{generic.Name}<{string.Join(", ", generic.TypeArguments.Select(TranspileTypeReference))}>",
                ArrayTypeReference array => $"{TranspileTypeReference(array.ElementType)}[]",
                NullableTypeReference nullable => $"{TranspileTypeReference(nullable.InnerType)}?",
                TupleTypeReference tuple => $"({string.Join(", ", tuple.Elements.Select(element => element.Name != null ? $"{TranspileTypeReference(element.Type)} {element.Name}" : TranspileTypeReference(element.Type)))})",
                FunctionTypeReference function => TranspileFunctionType(function),
                _ => "object"
            };
        }

        private static string TranspileFunctionType(FunctionTypeReference function)
        {
            if (function.ReturnType is SimpleTypeReference { Name: "void" })
            {
                return function.ParameterTypes.Count == 0
                    ? "Action"
                    : $"Action<{string.Join(", ", function.ParameterTypes.Select(TranspileTypeReference))}>";
            }

            var allTypes = function.ParameterTypes
                .Select(TranspileTypeReference)
                .Append(TranspileTypeReference(function.ReturnType))
                .ToList();

            return $"Func<{string.Join(", ", allTypes)}>";
        }

        private static string GetNamespaceName(CompilationUnit unit)
        {
            return unit.Namespace?.Name
                ?? unit.Package?.Name
                ?? string.Empty;
        }

        private sealed record TopLevelFunctionStub(string Namespace, FunctionDeclaration Function);

        private void Write(string text)
        {
            _output.Append(new string(' ', _indentLevel * 4));
            _output.Append(text);
        }

        private void WriteLine(string text = "")
        {
            if (text.Length == 0)
            {
                _output.AppendLine();
                return;
            }

            _output.Append(new string(' ', _indentLevel * 4));
            _output.AppendLine(text);
        }
    }
}
