<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>NSharpLang.Build.Tasks</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Framework" Version="18.0.2" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../NSharpLang.Compiler/Compiler.csproj" />
  </ItemGroup>

  <ItemGroup Condition="Exists('$(OutputPath)NSharpLang.Compiler.Dogfood.dll')">
    <Reference Include="NSharpLang.Compiler.Dogfood">
      <HintPath>$(OutputPath)NSharpLang.Compiler.Dogfood.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="NSharpLang.Build.targets" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
