<Project Sdk="NSharpLang.Sdk" InitialTargets="GenerateBootstrapProjectConfig">
  <Target
    Name="GenerateBootstrapProjectConfig"
    Condition="!Exists('$(MSBuildProjectDirectory)/obj/project.g.props')">
    <MakeDir Directories="$(MSBuildProjectDirectory)/obj" />
    <WriteLinesToFile
      File="$(MSBuildProjectDirectory)/obj/project.g.props"
      Overwrite="true"
      Lines="&lt;Project xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;&#x0A;  &lt;PropertyGroup&gt;&#x0A;    &lt;TargetFramework&gt;net10.0&lt;/TargetFramework&gt;&#x0A;    &lt;OutputType&gt;Library&lt;/OutputType&gt;&#x0A;    &lt;_NSharpOriginalOutputType&gt;Library&lt;/_NSharpOriginalOutputType&gt;&#x0A;    &lt;AssemblyName&gt;NSharpLang.Compiler.BootstrapServices&lt;/AssemblyName&gt;&#x0A;    &lt;NSharpCompilationBackend&gt;il&lt;/NSharpCompilationBackend&gt;&#x0A;    &lt;NSharpTestFramework&gt;xunit&lt;/NSharpTestFramework&gt;&#x0A;    &lt;NSharpEmitValidateWithLegacyAnalysis&gt;false&lt;/NSharpEmitValidateWithLegacyAnalysis&gt;&#x0A;    &lt;_NSharpBaseSdk&gt;Microsoft.NET.Sdk&lt;/_NSharpBaseSdk&gt;&#x0A;  &lt;/PropertyGroup&gt;&#x0A;&lt;/Project&gt;" />
  </Target>
</Project>
