name: WebApi
version: 1.0.0
entry: Program.nl
backend: il
outputType: exe
targetFramework: net10.0
sdk: Microsoft.NET.Sdk.Web

dependencies:
  - framework: Microsoft.AspNetCore.App
  - nuget: Swashbuckle.AspNetCore
    version: 7.2.0
  - nuget: Microsoft.AspNetCore.OpenApi
    version: 9.0.0

language:
  asyncDefaultType: ValueTask
