// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'quick-start',
        'getting-started',
        'basics',
        'language-tour',
      ],
    },
    {
      type: 'category',
      label: 'Language Guide',
      collapsed: false,
      items: [
        'functions',
        'types',
        'pattern-matching',
        'systems',
      ],
    },
    {
      type: 'category',
      label: 'Tooling',
      collapsed: false,
      items: [
        'cli-reference',
        'debugging',
        'ci-cd',
      ],
    },
    {
      type: 'category',
      label: 'Coming From Another Language',
      collapsed: true,
      items: [
        'for-go-developers',
      ],
    },
    {
      // Autogenerated on purpose: this list was written by hand, and three of the first five pages
      // (NL105, NL324, NL325) were unreachable from the site's navigation as a result.
      type: 'category',
      label: 'Error Reference',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'errors' }],
    },
  ],
};

export default sidebars;
